name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16.20'
    - name: Install root dependencies
      run: npm ci
    - name: Install tests dependencies
      run: npm ci
      working-directory: example_plugin_tests/
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: example_plugin_tests/
    - name: Run Playwright tests
      run: npm run test
      working-directory: example_plugin_tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: example_plugin_tests/playwright-report/
        retention-days: 30
